kind: Service
apiVersion: v1
metadata:
  name: api-server
  labels:
    name: api-server
spec:
  ports:
    - nodePort: 30164 
      port: 8080      
      targetPort: 8080  
      protocol: TCP
  selector:           
    app: api-server
  type: NodePort       

---
apiVersion: apps/v1 
kind: Deployment    
metadata:              
  name: api-server
spec:                
  selector:         
    matchLabels:
      app: api-server
  replicas: 1        
  template:
    metadata:
      labels:        
        app: api-server
    spec:
      containers:
        - name: api-server
          image: hdeok/api-server:1.5
          ports:
            - containerPort: 8080                
          env:   # Setting Enviornmental Variables
          - name: DB_HOST   # Setting Database host address from configMap
            valueFrom: 
              configMapKeyRef:
                name: db-conf  # name of configMap
                key: host
          - name: DB_NAME  # Setting Database name from configMap
            valueFrom:
              configMapKeyRef:
                name: db-conf 
                key: name
          - name: DB_USERNAME  # Setting Database username from Secret
            valueFrom:
              secretKeyRef:
                name: db-credentials # Secret Name
                key: username
          - name: DB_PASSWORD # Setting Database password from Secret
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: password     
        