server:
 port: 8081

spring: 
  name: restapitest
 
  config:
    activate:
      on-profile: dev-h2 # 환경이름설정

  datasource:
    
    # h2 memory
    ################
    #driver-class-name: org.h2.Driver
    #jdbc-url: jdbc:h2:mem:testdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE #mysql 모드 설정
    #username: sa
    #password:

    ################
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    jdbc-url: jdbc:log4jdbc:h2:mem:testdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE #mysql 모드 설정
    username: sa
    password:
    
    # h2 file
    ################
    #driver-class-name: org.h2.Driver  #h2 드라이버 설정
    #jdbc-url: jdbc:h2:file:~/testdb
    #username: sa
    #password:
    
    ################
    #driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy  # log4jdbc 용 
    #jdbc-url: jdbc:log4jdbc:h2:file:~/testdb    # log4jdbc 용
    #username: sa
    #password:
    

  jpa:
    hibernate:
      ddl-auto: create-drop # update # create # create-drop # 애플리케이션을 시작할때 데이터베이스를 초기화하고 다시 테이블 생성    
      # 엔티티로 등록된 클래스와 매핑되는 테이블을 자동으로 생성(create)해준다.기존에 해당 클래스와 매핑되는 테이블이 존재한다면 기존 테이블을 삭제(drop)하고 테이블을 생성한다.
      
    show-sql: true  #jpa가 수행하는 쿼리 출력
    properties:
      hibernate:
        format_sql: true # 실행되는 쿼리를 보여줌, 쿼리출력 가독성 향상, 한줄이 아니라 여러줄로 출력
        dialect: org.hibernate.dialect.MySQL8Dialect
  
  sql:
    init:
      mode: always
      # 모든 데이터베이스에 sql script를 동작시키는 'always', 
      # embedded(내장) 데이터베이스만 sql 스크립트를 동작시키는 'embedded', 
      # 모든 데이터베이스에 sql script를 동작시키지 않는 'never'

  h2:
    console:
      enabled: true
      path: /h2-console   # http://localhost:8081/h2-console
      settings:
        web-allow-others: true  # 리모트서버에 앱이 설치되어도 접속이 가능하도록 한다
        
        

logging:
  level:
    
    com.hds.restapitest.mapper: debug    # 각자의 패키지명을 적어주세요
    
    # log4jdbc 관련 로그 레벨 설정
    jdbc.sqltiming: info 

    jdbc.sqlonly: off #error 
    jdbc.audit: off #error 
    jdbc.resultset: off #error 
    jdbc.resultsettable: off #error 
    jdbc.connection: off #error 


    com.zaxxer.hikari.HikariDataSource: off #ERROR  
    org.springframework.web: off #ERROR

