apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  root-password: "YWRtaW4xMjM=" # admin123
  password: "dGVzdHVzZXJAMTIz" # testuser@123
stringData:
  root-username: "root" # root
  username: "testuser" # username